defaults:
  - _self_
  - model: gvhmr/gvhmr_pl_demo
  - network: gvhmr/relative_transformer
  - endecoder: gvhmr/v1_amass_local_bedlam_cam

pipeline:
  _target_: hmr4d.model.gvhmr.pipeline.gvhmr_pipeline.Pipeline
  args_denoiser3d: ${network}
  args:
    endecoder_opt: ${endecoder}
    normalize_cam_angvel: True
    weights: null
    static_conf: null

ckpt_path: inputs/checkpoints/gvhmr/gvhmr_siga24_release.ckpt

# ================================ #
#          global setting          #
# ================================ #

video_name: buildbot_example_frames_cam3
output_root: outputs/demo
output_dir: "${output_root}/${video_name}"
preprocess_dir: ${output_dir}/preprocess
video_path: "${preprocess_dir}/0_input_video.mp4"
# frames_path: ???
main_view_cam: 'cam_3'
reference_object_keypoints_3D: # [meters]
 - [0.0, 0.0, 0.0]  # the table corners in this case (ordered clockwise from top left)
 - [1.8, 0.0, 0.0]
 - [1.8, 1.0, 0.0]
 - [0.0, 1.0, 0.0]
reference_object_keypoints: # [pixels]
# the table corners in this case (ordered clockwise from top left)
  cam_1:
    - [133,  30]
    - [533,  28]
    - [513, 295]
    - [155, 298]
  cam_2:
    - [309, 278]
    - [599, 361]
    - [425, 516]
    - [130, 337]
  cam_3:
    - [581, 263]
    - [614, 484]
    - [190, 415]
    - [350, 257]

# Options
static_cam: False
verbose: False
use_dpvo: False
f_mm: 1.98 #null  # focal length of fullframe camera in mm
fps: 15

paths:
  bbx: ${preprocess_dir}/bbx.pt
  bbx_xyxy_video_overlay: ${preprocess_dir}/bbx_xyxy_video_overlay.mp4
  vit_features: ${preprocess_dir}/vit_features.pt
  vitpose: ${preprocess_dir}/vitpose.pt
  vitpose_video_overlay: ${preprocess_dir}/vitpose_video_overlay.mp4
  hmr4d_results: ${output_dir}/hmr4d_results.pt
  incam_video: ${output_dir}/1_incam.mp4
  global_video: ${output_dir}/2_global.mp4
  incam_global_horiz_video: ${output_dir}/${video_name}_3_incam_global_horiz.mp4
  slam: ${preprocess_dir}/slam_results.pt
